//! PARA COUNTRIES
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_DETAIL = "GET_COUNTRY_BY_DETAIL";

//! PARA ACTIVITIES
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITY_DETAIL = "GET_ACTIVITY_DETAIL";

//!PARA BÚSQUEDA
export const SEARCH_COUNTRY_BY_NAME = "SEARCH_COUNTRY";
