//! PARA COUNTRIES
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_DETAIL = "GET_COUNTRY_BY_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL";

//! PARA ACTIVITIES
export const GET_ALL_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITY_DETAIL = "GET_ACTIVITY_DETAIL";
export const DELETE_ACTIVIY = "DELETE_ACTIVITY";
export const PUT_ACTIVITY = "PUT_ACTIVITY";

//!PARA BÚSQUEDA
export const SEARCH_COUNTRY_BY_NAME = "SEARCH_COUNTRY";
