//! PARA COUNTRIES
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_DETAIL = "GET_COUNTRY_BY_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL";

//! PARA ACTIVITIES
export const GET_ALL_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITY_DETAIL = "GET_ACTIVITY_DETAIL";
export const DELETE_ACTIVIY = "DELETE_ACTIVITY";
export const PUT_ACTIVITY = "PUT_ACTIVITY";

//!PARA BÚSQUEDA
export const SEARCH_COUNTRY_BY_NAME = "SEARCH_COUNTRY";

//!FILTROS
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";

//!ORDENAMIENTOS
export const SORT_BY_POPULATION = "SORT_BY_POPULATION";
export const SORT_BY_ORDER_ABC = "SORT_BY_ORDER_ABC";

//!REFRESCAR FILTROS
export const RELOAD_FILTERS = "RELOAD_FILTERS";
